@SchedulePlanner_HostAddress = http://localhost:5126

###
POST http://localhost:5126/api/ScheduleEntries
Content-Type: application/json

{
  "date": "2026-08-15",
  "startTime": "09:00:00",
  "endTime": "17:00:00",
  "allDay": false,
  "entryType": "Working",
  "workLocation": "Office",
  "notes": "Test entry"
}

###