export const WEEKLY_TARGET_HOURS = 42
export const RED_THRESHOLD_HOURS = 40
export const YELLOW_THRESHOLD_HOURS = 10

export const BUSINESS_DAYS_PER_WEEK = 5
export const DAILY_TARGET_HOURS = WEEKLY_TARGET_HOURS / BUSINESS_DAYS_PER_WEEK
export const DAILY_RED_THRESHOLD_HOURS = 1
